# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hidden Pugmarks
tagline:          'The Adventure Continues…'
description:      'The Adventure Continues…'
url:              https://hiddenpugmarks.github.io
# url:              http://127.0.0.1:4000
baseurl:          /

author:
  name:           'Hidden Pugmarks'
  url:            https://hiddenpugmarks.github.io/

gems : ['jekyll-paginate', 'jekyll-gist']
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:
